version: '3'
services:
  wordpress:
    build: . # カレントディレクトリのDockerfileでイメージをビルド
    image: wordpress
    ports:
      - '80:80' # ローカルのport80でコンテナのport80にアクセスできるようにする
    environment:
      WORDPRESS_DB_HOST: fargate-wordpress-database-2.cw6pwdknkvql.ap-northeast-1.rds.amazonaws.com # rdsのエンドポイント
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: rootpass
    volumes:
      - .:/var/www/html
    restart: always